Feature: example architecture
augusstoflavio/marvel-catalog pull request #3
Opened 2022-01-27 22:45 UTC by augusstoflavio

Cria exemplo de useCase com teste, usando o Mockito

2022-01-29 00:12 UTC, danilofneves requested changes

2022-01-29 00:12 UTC, danilofneves commented on domain/src/main/java/com/marvelcatalog/domain/useCase/GetCharacterUseCase.kt
> +                InvalidParameterException("A página tem que ser maior que 0")
Acredito que Mensagens e texto sejam preferencialmente declaradas no resource para fim de troca de idioma.

2022-01-29 01:01 UTC, augusstoflavio commented on domain/src/main/java/com/marvelcatalog/domain/useCase/GetCharacterUseCase.kt
> +                InvalidParameterException("A página tem que ser maior que 0")
Isso é uma coisa que eu fiquei na dúvida, na camada de domain eu não devo acessar o resource, qual deve ser o melhor jeito de enviar a mensagem? Criar um mapa de erro e retornar o código do erro?

2022-01-29 01:11 UTC, danilofneves commented on domain/src/main/java/com/marvelcatalog/domain/useCase/GetCharacterUseCase.kt
> +                InvalidParameterException("A página tem que ser maior que 0")
Isso, eu faço desse jeito. vc ja tem a instancia do erro, basta encapsular o mapper na camada de ui.

2022-01-30 12:52 UTC, augusstoflavio commented on domain/src/main/java/com/marvelcatalog/domain/useCase/GetCharacterUseCase.kt
> +                InvalidParameterException("A página tem que ser maior que 0")
Alterei, mas irei levantar essa dúvida com o pessoal lá do trabalho para ver se eles dão outras ideias

2022-02-01 18:20 UTC, danilofneves approved these changes

2022-02-01 19:02 UTC, merged